image: python:3.8-slim-buster

stages:
  - harness

e2e:chrome:
  stage: harness
  services:
    - selenium/standalone-chrome  
  before_script:
    - pip3 install -r requirements.txt  
  script:
    - python3 test_harness_flows.py