apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome
  labels:
    app: selenium-chrome
spec:
  ports:
  - port: 4444
    targetPort: 4444
    name: port4444
  selector:
    app: selenium-chrome
  type: NodePort
  sessionAffinity: None
